-- ##############################################################################
--  Schéma applicatif — tables, données, vues, fonctions / procédures, trigger
-- ##############################################################################
-- Connexion : utilisateur schéma (ex. rdv_app)
--
-- IMPORTANT — exécutez d’abord sql/01_installation/01_grants.sql en SYSTEM,
--             sinon CREATE FUNCTION / PROCEDURE / TRIGGER en bas peuvent échouer (ORA-01031).
--
-- Fuseau applicatif : Europe/Paris (TIMESTAMP en base sans fuseau).
-- Historique suppressions RDV : rempli par le trigger tr_rdv_hist_after_delete (fin du script). L’API ne fait que DELETE.
-- ##############################################################################


-- =============================================================================
-- NETTOYAGE OPTIONNEL
-- =============================================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER tr_rdv_hist_after_delete';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP FUNCTION fn_rdv_demo_count';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP PROCEDURE sp_rdv_demo_ping';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW v_accueil_resume';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW v_prochains_rdv';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE rendez_vous CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE rdv_suppressions_historique CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE patients CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE medecins CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE app_users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/


-- =============================================================================
-- TABLES & INDEX
-- =============================================================================
CREATE TABLE medecins (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR2(100) NOT NULL,
    specialite  VARCHAR2(120) NOT NULL
);

CREATE TABLE patients (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR2(100) NOT NULL,
    prenom      VARCHAR2(100) NOT NULL,
    cin         VARCHAR2(8),
    telephone   VARCHAR2(30),
    email       VARCHAR2(120),
    CONSTRAINT chk_patients_cin CHECK (
        cin IS NULL OR REGEXP_LIKE(cin, '^[A-Z]{1,2}[0-9]{5,6}$')
    ),
    CONSTRAINT uk_patients_cin UNIQUE (cin)
);

CREATE TABLE app_users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(80) NOT NULL UNIQUE,
    password_hash   VARCHAR2(512) NOT NULL
);

CREATE TABLE rendez_vous (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      NUMBER NOT NULL,
    medecin_id      NUMBER NOT NULL,
    date_heure      TIMESTAMP NOT NULL,
    motif           VARCHAR2(500),
    statut          VARCHAR2(30) DEFAULT 'planifie'
                    CONSTRAINT chk_statut CHECK (statut IN ('planifie', 'confirme', 'annule', 'termine')),
    duree_minutes   NUMBER DEFAULT 30,
    CONSTRAINT fk_rdv_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_rdv_medecin FOREIGN KEY (medecin_id) REFERENCES medecins(id)
);

CREATE INDEX idx_rdv_date ON rendez_vous(date_heure);
CREATE INDEX idx_rdv_patient ON rendez_vous(patient_id);

CREATE TABLE rdv_suppressions_historique (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ancien_rdv_id   NUMBER NOT NULL,
    patient_id      NUMBER NOT NULL,
    medecin_id      NUMBER NOT NULL,
    date_heure      TIMESTAMP NOT NULL,
    motif           VARCHAR2(500),
    statut          VARCHAR2(30),
    duree_minutes   NUMBER,
    supprime_le     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_rdv_hist_supprime ON rdv_suppressions_historique(supprime_le);


-- =============================================================================
-- DONNÉES DE DÉMO
-- =============================================================================
INSERT INTO app_users (username, password_hash)
VALUES (
    'demo',
    'scrypt:32768:8:1$foFYFdQMUfqLGedp$f854ef2532e65725982e902326a364eaf9147f4f2ab5257515abb54e76891fe70be6691bcfa1392e399cdfcbcca6335f37e32ef4bdf445c4792e60d46be1befb'
);

INSERT INTO medecins (nom, specialite) VALUES ('Youssef', 'Cardiologie');
INSERT INTO medecins (nom, specialite) VALUES ('Yahya', 'Médecine générale');

INSERT INTO patients (nom, prenom, cin, telephone, email)
VALUES ('Hajji', 'Soufiane', 'AB123456', '0612345678', 'soufiane@gmail.com');
INSERT INTO patients (nom, prenom, cin, telephone, email)
VALUES ('El-Alaoui', 'Ilham', 'CD987654', '0698765432', 'ilham@gmail.com');

INSERT INTO rendez_vous (patient_id, medecin_id, date_heure, motif, statut, duree_minutes)
VALUES (1, 1, SYSTIMESTAMP + INTERVAL '2' DAY, 'Contrôle tension', 'planifie', 30);
INSERT INTO rendez_vous (patient_id, medecin_id, date_heure, motif, statut, duree_minutes)
VALUES (2, 2, SYSTIMESTAMP + INTERVAL '5' DAY, 'Consultation routine', 'confirme', 30);

COMMIT;


-- =============================================================================
-- VUE — accueil (une ligne : effectifs patients / médecins / RDV)
--        GET /api/accueil
-- =============================================================================
CREATE OR REPLACE VIEW v_accueil_resume AS
SELECT
    (SELECT COUNT(*) FROM patients)   AS nb_patients,
    (SELECT COUNT(*) FROM medecins)  AS nb_medecins,
    (SELECT COUNT(*) FROM rendez_vous WHERE statut NOT IN ('annule', 'termine')) AS nb_rdv
FROM dual;


-- =============================================================================
-- VUE — RDV « actifs » (planifié ou confirmé), toutes dates — même périmètre que nb_rdv
--        GET /api/accueil/prochains-rdv — tri dans la requête Python
-- =============================================================================
CREATE OR REPLACE VIEW v_prochains_rdv AS
SELECT
    r.id,
    r.date_heure,
    r.motif,
    r.statut,
    r.duree_minutes,
    p.nom           AS patient_nom,
    p.prenom        AS patient_prenom,
    m.nom           AS medecin_nom,
    m.specialite    AS medecin_specialite
FROM rendez_vous r
JOIN patients p ON p.id = r.patient_id
JOIN medecins m ON m.id = r.medecin_id
WHERE r.statut NOT IN ('annule', 'termine');


-- =============================================================================
-- EXEMPLE — FONCTION PL/SQL (démo pédagogique)
-- =============================================================================
CREATE OR REPLACE FUNCTION fn_rdv_demo_count
RETURN NUMBER
AUTHID DEFINER
IS
    v_n NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_n FROM rendez_vous;
    RETURN v_n;
END;
/


-- =============================================================================
-- EXEMPLE — PROCÉDURE PL/SQL (démo pédagogique)
-- =============================================================================
CREATE OR REPLACE PROCEDURE sp_rdv_demo_ping
AUTHID DEFINER
IS
BEGIN
    NULL;
END;
/


-- =============================================================================
-- TRIGGER — historique sur DELETE
-- =============================================================================
CREATE OR REPLACE TRIGGER tr_rdv_hist_after_delete
    AFTER DELETE ON rendez_vous
    FOR EACH ROW
BEGIN
    INSERT INTO rdv_suppressions_historique (
        ancien_rdv_id,
        patient_id,
        medecin_id,
        date_heure,
        motif,
        statut,
        duree_minutes,
        supprime_le
    ) VALUES (
        :OLD.id,
        :OLD.patient_id,
        :OLD.medecin_id,
        :OLD.date_heure,
        :OLD.motif,
        :OLD.statut,
        :OLD.duree_minutes,
        SYSTIMESTAMP
    );
END;
/
